language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coverage
  - pip install pytest-django
  - pip install pytest-cov
  - pip install codecov
script:
  - cd mysite
  - pytest
after_success:
    - codecov